### ISSUE TITLE
iOS crashes on run

### ISSUE THREAD

**Issue by mortezaezzabady** [tapsellorg/TapsellPlusSDK-UnitySample#5]
Hello,
I've added the TapsellPlus framework to my application via cocoapods, and followed your guide, however, the application crashes and prints this:
```
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /private/var/containers/Bundle/Application/9A031BFB-CA31-48C4-88CD-6D6DCB14D0E9/ProductName.app/Frameworks/TapsellPlus.framework/TapsellPlus
  Reason: image not found
```

### Things I tried:

- Clearing xcode derived data folder
- Cleaning the project
- adding the -ObjC flag 
- Always Embed Standard Swift Libraries = YES
- tried with and without use_frameworks! flag in podfile
- upgraded cocoapods to latest version

none of the above worked :(

**Comment by mtoori** [comment]
Hi,
About things you have tried, having "Always Embed Standard Swift Libraries" and "use_frameworks!" flags are always correct. "-ObjC" flag is needed if your project is in Objective-C, or your project is exported from Unity.

Can you give more details about your system information, like macOS and Xcode version?
Is your project exported from Unity, and if it is, which version of unity are you using?

**Comment by mortezaezzabady** [comment]
It's a project exported from unity.

### Versions
macOS Mojave 10.14.5 (18F132)
Xcode 10.3 (10G8)
Unity: 2017.4.25

**Comment by mtoori** [comment]
I couldn't reproduce your mentioned problem on our systems.
Can you provide a sample project?
