### ISSUE TITLE
conflict with admob

### ISSUE THREAD

**Issue by hamzemp** [tapsellorg/TapsellPlusSDK-UnitySample#6]
سلام ، خسته نباشید.
مثل اینکه کتابخانه های تپسل پلاس با ادموب به مشکل برمیخورن . اصلا هیچ ویدیویی نشون نمیده !
مشکل از کجاست ؟
تپسل پلاس به تنهایی کار  میکنه ولی با ادموب نه
یک ماهه همه ی راه حل های ممکن رو تست کردم .

**Comment by behdad222** [comment]
تو logcat چه اروری میاد؟
